# Hydra-based DQN Training Configuration
# This config uses the agent/dqn.yaml for agent parameters

defaults:
  - agent: dqn
  - _self_

# Experiment settings
experiment:
  name: "sevens_dqn_hydra"
  seed: 42
  device: "cpu"  # 'cpu' or 'cuda'

# Environment settings
env:
  num_players: 4

# Training settings
training:
  num_episodes: 10000
  eval_freq: 100  # Evaluate every N episodes
  save_freq: 1000  # Save checkpoint every N episodes
  log_freq: 10  # Log progress every N episodes

# Logging
logging:
  level: "INFO"
  log_dir: "logs"
  tensorboard: false
